spring:
  datasource:
    url: jdbc:mysql://192.168.8.205:3306/soc
    username: dev
    password: devpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
    host: 192.168.8.205
    password: 123456
    port: 6379
server:
  port: 8080